name: push-docker-image
on:
  workflow_dispatch:
jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile-7
        target: base
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:centos7
        platforms: linux/amd64,linux/arm64
        push: true
        # See: https://github.com/community/community/discussions/45969
        provenance: false
